players:
- Neoh
- SnK
- Midazo
- Lanstark
- Itah
- Magad
- Swed
- Tsubasa
- Magma
- Karanyyan
- Qt
- Tchitcha
- Joueur Solide
- MFL D1
decks:
  meta:
  - AS Aggro
  - BP Blurple
  - RG Songs
  - AS Reanimator
  - GS Pirates
  - BS Midrange
  - RP Evasive
  - GP Evasive
  - GP Control
  - RS Midrange
  contenders:
  - RB Items
  - BS Ally
options:
  allow_draws: true
  show_counts_on_matrix: true
  heatmap_midpoint: 50.0
  sort_rows_by_global_wr: true
