players:
- Lanstark
- Swed
- Karanyyan
- Lorcadys
- Di칟se
- Gadock
- Ultera
- Aymx
- FoodZaro
- Gon20
- G칠g칠
- Jerome
- KaraNyyan
- Kind
- LowlowJ
- Nazsan
- Pizzaro
- Scipio
- Sergent tibs
- Sethit
- LeF
- Kapapeur
- Poicreux
- Purphoros
- LORCANITO
- TOURNOIS
- Autres
decks:
  meta:
  - 游릳游릵yp
  - 游릳游릴yg
  - 游릳游린yr
  - 游릳游릱yb
  - 游릳拘랓s
  - 游릵游릴pg
  - 游릵游린pr
  - 游릵游릱pb
  - 游릵拘랋s
  - 游릴游린gr
  - 游릴游릱gb
  - 游릴拘랂s
  - 游린游릱rb
  - 游린拘rs
  - 游릱拘락s
  contenders: []
options:
  allow_draws: true
  show_counts_on_matrix: true
  heatmap_midpoint: 50.0
  sort_rows_by_global_wr: true
