players:
- Lanstark
- Swed
- Karanyyan
- Lorcadys
- DiÃ¨se
- Gadock
- Ultera
- Aymx
- FoodZaro
- Gon20
- GÃ©gÃ©
- Jerome
- KaraNyyan
- Kind
- LowlowJ
- Nazsan
- Pizzaro
- Scipio
- Sergent tibs
- Sethit
- LeF
- Kapapeur
- Poicreux
- Purphoros
decks:
  meta:
  - ğŸŸ¨ğŸŸª
  - ğŸŸ¨ğŸŸ©
  - ğŸŸ¨ğŸŸ¥
  - ğŸŸ¨ğŸŸ¦
  - ğŸŸ¨â¬œ
  - ğŸŸªğŸŸ©
  - ğŸŸªğŸŸ¥
  - ğŸŸªğŸŸ¦
  - ğŸŸªâ¬œ
  - ğŸŸ©ğŸŸ¥
  - ğŸŸ©ğŸŸ¦
  - ğŸŸ©â¬œ
  - ğŸŸ¥ğŸŸ¦
  - ğŸŸ¥â¬œ
  - ğŸŸ¦â¬œ
  contenders: []
options:
  allow_draws: true
  show_counts_on_matrix: true
  heatmap_midpoint: 50.0
  sort_rows_by_global_wr: true
