players:
- Lanstark
- Swed
- Karanyyan

decks:
  meta:
  - BS
  - PS  
  contenders:
  - RB 

options:
  allow_draws: true
  show_counts_on_matrix: true
  heatmap_midpoint: 50.0
  sort_rows_by_global_wr: true
