players:
  - swed
  - KaraNyyan
decks:
  meta:
  - PS
  - VV
  - BS
  contenders:
  - GS
options:
  allow_draws: true
  show_counts_on_matrix: true
  heatmap_midpoint: 50.0
  sort_rows_by_global_wr: true
